spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${EDUPILOT_DB_URL}
    username: ${EDUPILOT_DB_USERNAME}
    password: ${EDUPILOT_DB_PASSWORD}

logging:
  level:
    root: INFO
