package io.edupilot.material;

public enum MaterialFailureReason {
	EXTRACTION_FAILED,
	PAGE_LIMIT_EXCEEDED,
	SCHEDULING_FAILED,
	UNSUPPORTED_FORMAT,
	ENCRYPTED_PDF,
	NO_TEXT_CONTENT,
	FILE_TOO_LARGE
}
